using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace GSS.Generators
{
    [Generator]
    public sealed partial class ApiBindingGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var profileDeclarations = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (s, _) => IsPotentialProfile(s),
                    transform: static (ctx, _) => GetProfileInfo(ctx))
                .Where(static m => m != null);

            var compilationAndProfiles = context.CompilationProvider.Combine(profileDeclarations.Collect());

            context.RegisterSourceOutput(compilationAndProfiles, 
                static (spc, source) => Execute(spc, source.Left, source.Right!));
        }

        private static bool IsPotentialProfile(SyntaxNode node)
        {
            return node is ClassDeclarationSyntax classDecl && classDecl.BaseList != null;
        }

        private static ProfileInfo? GetProfileInfo(GeneratorSyntaxContext context)
        {
            var classDecl = (ClassDeclarationSyntax)context.Node;
            var symbol = context.SemanticModel.GetDeclaredSymbol(classDecl) as INamedTypeSymbol;

            if (symbol == null) return null;

            var baseType = symbol.BaseType;
            while (baseType != null)
            {
                if (baseType.Name == "ApiProfile" && baseType.IsGenericType)
                {
                    var targetType = baseType.TypeArguments[0];
                    return new ProfileInfo(
                        symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                        targetType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                    );
                }
                baseType = baseType.BaseType;
            }

            return null;
        }

        private static void Execute(SourceProductionContext context, Compilation compilation, ImmutableArray<ProfileInfo> profiles)
        {
            if (profiles.IsDefaultOrEmpty) return;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using GSS.Kernel.Api.Registry;");
            sb.AppendLine();
            sb.AppendLine("namespace GSS.Runtime.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    public static class ApiBindingExtensions");
            sb.AppendLine("    {");
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// Automatically registers all discovered API profiles in the project.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        public static ApiRegistryBuilder RegisterAllProfiles(this ApiRegistryBuilder builder)");
            sb.AppendLine("        {");

            foreach (var profile in profiles.Distinct())
            {
                sb.AppendLine($"            builder.Register(new {profile.ProfileFullName}());");
            }

            sb.AppendLine("            return builder;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            context.AddSource("GssApiBindings.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }
    }
}