using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace GSS.Generators
{
	[Generator]
	public sealed class ApiBindingGenerator : IIncrementalGenerator
	{
		public void Initialize(IncrementalGeneratorInitializationContext context)
		{
			var profileClasses = context.SyntaxProvider
				.CreateSyntaxProvider(
					predicate: static (s, _) => IsClassWithBaseList(s),
					transform: static (ctx, _) => GetApiProfileTarget(ctx))
				.Where(static m => m != null);

			context.RegisterSourceOutput(profileClasses, static (spc, targetType) => ExecuteGeneration(spc, targetType!));
		}

		private static bool IsClassWithBaseList(SyntaxNode node)
		{
			return node is ClassDeclarationSyntax classDecl && classDecl.BaseList != null;
		}

		private static string? GetApiProfileTarget(GeneratorSyntaxContext context)
		{
			var classDecl = (ClassDeclarationSyntax)context.Node;

			foreach (var baseType in classDecl.BaseList!.Types)
			{
				if (baseType.Type is GenericNameSyntax genericName &&
					genericName.Identifier.Text == "ApiProfile")
				{
					return genericName.TypeArgumentList.Arguments.FirstOrDefault()?.ToString();
				}
			}

			return null;
		}

		private static void ExecuteGeneration(SourceProductionContext context, string targetType)
		{
			var source = new StringBuilder();
			source.AppendLine("// <auto-generated/>");
			source.AppendLine("using System;");
			source.AppendLine("using GSS.Core.ApiBinding.Models;");
			source.AppendLine("using GSS.Core.ApiBinding.Abstractions;");
			source.AppendLine();
			source.AppendLine("namespace GSS.Runtime.Generated");
			source.AppendLine("{");
			source.AppendLine($"    public static class {targetType}Bindings");
			source.AppendLine("    {");
			source.AppendLine($"        public static void Register(IApiRegistry registry)");
			source.AppendLine("        {");
			source.AppendLine($"            // AOT Bindings for {targetType} injected here");
			source.AppendLine($"            // Generates static delegates for zero-allocation IL2CPP compatibility");
			source.AppendLine("        }");
			source.AppendLine("    }");
			source.AppendLine("}");

			context.AddSource($"{targetType}Bindings.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
		}
	}
}